[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m hasl_calendar.migrate && gunicorn 'hasl_calendar.app:app' --bind 0.0.0.0:$PORT --workers 2"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
